343 UI Update Admin Tools Scan History table
cisagov/XFD pull request #364
Opened 2024-06-25 15:06 UTC by hawkishpolicy

#  #
- Updated ScanTasksView table to MUI Data Grid X
## 🗣 Description ##
- Refactored code to use new Data Grid
- Added aria-labels to Details Icon Button
- Corrected tab indexing of table
- Built new Scan Name dropdown filter
- Built new Scan Status dropdown filter
- Built new modal to house Logs, Inout, Output, and Actions.

## 💭 Motivation and context ##
- Brings Scans History inline with new Organizations table.
- Updates style.
- Improves UX.
- Meets 508 compliance.
- Closes #343 

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##
![Screenshot 2024-06-25 at 10 37 20 AM](https://github.com/cisagov/XFD/assets/123108455/a4a3c60e-fd28-4776-a566-ce10890d63f3)
![Screenshot 2024-06-25 at 11 04 20 AM](https://github.com/cisagov/XFD/assets/123108455/91c0d9b9-fe72-4951-b261-b42a2cba5e3b)
![Screenshot 2024-06-25 at 11 04 28 AM](https://github.com/cisagov/XFD/assets/123108455/61a57507-f3a5-48a2-b188-ba832d943b51)

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-06-25 15:52 UTC, aloftus23 requested changes
- [x] Filtering of Name and Status only works if the value exists. Say, dnstwist hasn't been run ever and you filter the Name by dnstwist; the table doesn't change at all. Instead should say No results or something
- [ ] The table needs to be sorted by the Created At column where the first entry is the most recent. I believe right now it is doing the opposite

Otherwise looks good!

2024-06-26 14:19 UTC, aloftus23 approved these changes
Looks good!

2024-06-26 15:08 UTC, schmelz21 approved these changes
Looks good...

2024-06-26 15:08 UTC, merged

2024-06-26 17:55 UTC, cduhn17 commented on frontend/src/pages/Scans/ScanTasksView.tsx
> +        // if (result.length === 0) return;
Is this commented code needed?