modified searchbar contrast 4E4E4E for better visibility
cisagov/XFD pull request #406
Opened 2024-07-05 15:53 UTC by lwersiy

#  #

## 🗣 Description ##

Modified the crossfeed search bar to a darker contrast for better viewing

## 🧪 Testing ##
Tested on crossfeed local. 

## 📷 Screenshots (if appropriate) ##

![Screenshot 2024-07-05 at 11 47 41 AM](https://github.com/cisagov/XFD/assets/124970569/bb24200b-5988-4478-95e9-91939d4dae21)

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-07-10 15:34 UTC, hawkishpolicy requested changes
The search icon color needs to be changed as well.

2024-07-10 19:54 UTC, chrtorres approved these changes
LGTM

2024-07-10 20:19 UTC, hawkishpolicy approved these changes

2024-07-11 13:18 UTC, schmelz21 approved these changes

2024-07-11 13:20 UTC, merged