Resolved Server Side filtering bug (CRASM-397)
cisagov/XFD pull request #415
Opened 2024-07-08 20:01 UTC by hawkishpolicy

- Vulnerabilities table now maintains filters when calling new page of results.
- Filtered results are now paginated correctly.

#  #

## 🗣 Description ##
- Applied filters from the filter model change were not being passed to the Pagination Model state when loading a new page.
- On clicking the next page button, the pagination model's filters key was being set to empty and just returning all results as if it was a page refresh. 
- By adding a filters key/value pair to the setPaginationModel state inside the fetch Vulnerabilities function, the filters remain in place while a new page is loaded.

## 💭 Motivation and context ##
- Filtered results are maintained and properly paginated.
- Closes #399
- Closes CRASM-397 

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##
![Screenshot 2024-07-08 at 3 51 54 PM](https://github.com/cisagov/XFD/assets/123108455/6b13ac2e-5254-4847-8066-45806610964d)
![Screenshot 2024-07-08 at 3 52 02 PM](https://github.com/cisagov/XFD/assets/123108455/df92c19c-c2dc-4ea9-937f-813b3a5eba7b)
![Screenshot 2024-07-08 at 3 52 14 PM](https://github.com/cisagov/XFD/assets/123108455/11958c2c-7526-40c9-9bd0-83e3d8c6d44d)

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-07-09 18:55 UTC, nickviola approved these changes
LGTM

2024-07-10 16:50 UTC, ameliav requested changes
The domains table filtering is not working for me

2024-07-10 17:27 UTC, ameliav approved these changes
LGTM!

2024-07-10 17:36 UTC, schmelz21 approved these changes

2024-07-10 17:36 UTC, merged