Fixed server side filtering issue with All Domains table (CRASM-410)
cisagov/XFD pull request #418
Opened 2024-07-09 16:32 UTC by hawkishpolicy

- Fixed server side filtering in All Domains table.
- Applied filters are now maintained when loading a new page.
#  #

## 🗣 Description ##
- Updated filters values in paginationModel to be based off state.
- Filter model change now updates "filters" state then runs the fetchDomains function with the new filters.
- Updated setPaginationModel function inside fetchDomains to include filter values.

## 💭 Motivation and context ##
- Closes #416 
- Closes CRASM-410

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##
![Screenshot 2024-07-09 at 12 30 01 PM](https://github.com/cisagov/XFD/assets/123108455/1f0b947c-67e2-49dc-aba5-28b2752d93a5)
![Screenshot 2024-07-09 at 12 30 09 PM](https://github.com/cisagov/XFD/assets/123108455/9701295e-6260-46ea-a3ed-7c2b6dbd4571)

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-07-10 16:49 UTC, ameliav requested changes
The filtering is working, but the vulnerabilities table is out of date. Please merge the latest changes from develop

2024-07-10 17:22 UTC, ameliav approved these changes
Working for me now!

2024-07-11 14:29 UTC, chrtorres approved these changes
LGTM

2024-07-11 15:48 UTC, schmelz21 approved these changes

2024-07-11 15:48 UTC, merged