Remove console warnings and logs in browser
cisagov/XFD pull request #595
Opened 2024-09-06 20:51 UTC by ameliav

#  #

## 🗣 Description ##
Remove unused or legacy code causing console warnings and console logs.

## 💭 Motivation and context ##
Cleans up unused code and keeps the browser console cleaner.

## 🧪 Testing ##
No longer see the following:
- Unsupported style property warning
- Ignored route render warnings
- Unrecognized disableunderline warning
- Token Route Check string logs
- Inventory object string logs

## 📷 Screenshots ##
Remove the following console warnings and logs:
![image](https://github.com/user-attachments/assets/7fa57658-8dc1-49d7-965e-ba7278be58bd)
![image](https://github.com/user-attachments/assets/3d4eab41-8127-4330-8032-07525a90ac5f)
![image](https://github.com/user-attachments/assets/389bc36b-3f98-4d33-887a-d7e27ff7d1c3)
![image](https://github.com/user-attachments/assets/c1133ac6-9937-4217-8538-fcb337e6ca65)
![image](https://github.com/user-attachments/assets/c55b5db3-78fc-437c-8c78-79d23cb5d0a7)

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-09-06 21:25 UTC, hawkishpolicy requested changes
Need to remove the Redirect import.

What was the purpose of all these redirects anyways?

2024-09-06 21:40 UTC, chrtorres approved these changes

2024-09-09 15:06 UTC, ameliav commented
> Need to remove the Redirect import.
> 
> What was the purpose of all these redirects anyways?

It's legacy code so not sure why they were there because they were always being ignored.

2024-09-11 18:18 UTC, hawkishpolicy approved these changes

2024-09-11 19:08 UTC, jayjaybunce approved these changes

2024-09-11 20:08 UTC, nickviola approved these changes
LGTM

2024-09-12 17:05 UTC, schmelz21 approved these changes

2024-09-12 17:06 UTC, merged